# Generated by Django 4.2.30 on 2026-09-02 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('department', models.CharField(choices=[('OFFENSIVE', 'Offensive Security & Red Team'), ('SOC', 'Security Operations & Blue Team'), ('GRC', 'Governance, Risk & Compliance'), ('ENGINEERING', 'Autonomous Systems & Infrastructure'), ('RESEARCH', 'Threat Intelligence & Cryptography Lab')], default='OFFENSIVE', max_length=50)),
                ('location', models.CharField(default='Vadodara / Hybrid', max_length=100)),
                ('tag', models.CharField(default='OFFENSIVE · FULL-TIME', help_text='e.g. DEFENSE · 24/7 ROSTER', max_length=100)),
                ('icon', models.CharField(default='ShieldAlert', help_text='Lucide icon name: ShieldAlert, Search, CheckSquare, Code2, PenTool', max_length=50)),
                ('description', models.TextField()),
                ('responsibilities', models.JSONField(blank=True, default=list, help_text='List of responsibilities')),
                ('requirements', models.JSONField(blank=True, default=list, help_text='List of qualifications / skills')),
                ('subject', models.CharField(default='Application - Job Role', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide vacancy from website')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Role / Opening',
                'verbose_name_plural': 'Job Roles & Openings',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title_fallback', models.CharField(blank=True, help_text='Used if applying for Open Talent Alignment', max_length=150)),
                ('applicant_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('resume_file', models.FileField(help_text='PDF / DOCX resume', upload_to='resumes/%Y/%m/')),
                ('cover_note', models.TextField(blank=True)),
                ('linkedin_portfolio_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New Application'), ('REVIEWED', 'Under Technical Review'), ('INTERVIEW', 'Interview Scheduled'), ('OFFER', 'Offer Extended'), ('REJECTED', 'Archived / Not Selected')], default='NEW', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal reviewer comments')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, default='--', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='careers.jobrole')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
