# Generated by Django 4.2.30 on 2026-09-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume_file',
            field=models.FileField(blank=True, help_text='PDF / DOCX resume', null=True, upload_to='resumes/%Y/%m/'),
        ),
    ]
