# Generated by Django 4.2.30 on 2026-09-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyIncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=150)),
                ('emergency_email', models.EmailField(max_length=254)),
                ('emergency_phone', models.CharField(max_length=40)),
                ('breach_type', models.CharField(choices=[('RANSOMWARE', 'Ransomware / Encrypted Systems'), ('ACTIVE_INTRUSION', 'Active Cyber Intrusion / Lateral Movement'), ('DATA_EXFILTRATION', 'Suspected Data Exfiltration'), ('ZERO_DAY', 'Zero-Day / Critical Vulnerability Exploitation'), ('DDOS', 'Severe Distributed Denial of Service (DDoS)'), ('OTHER', 'Other Critical Security Breach')], default='RANSOMWARE', max_length=50)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical (Operations Halted)'), ('HIGH', 'High (Production Impacted)'), ('MEDIUM', 'Medium (Contained / Suspicious)')], default='CRITICAL', max_length=20)),
                ('_encrypted_payload', models.TextField(help_text='AES encrypted incident scope, ransom notes, and affected assets', verbose_name='Encrypted Incident Details')),
                ('sla_deadline_hours', models.PositiveIntegerField(default=4, help_text='Target response SLA in hours')),
                ('status', models.CharField(choices=[('ACTIVE_DISPATCH', 'Active Dispatch (Sub-4-Hour SLA Triggered)'), ('TRIAGED', 'Triaged / Containment In Progress'), ('CONTAINED', 'Threat Contained'), ('REMEDIATED', 'Remediated & Forensic Report Delivered'), ('CLOSED', 'Closed')], default='ACTIVE_DISPATCH', max_length=30)),
                ('lead_incident_commander', models.CharField(blank=True, max_length=150)),
                ('admin_notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, default='--', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DFIR Emergency Incident Alert',
                'verbose_name_plural': 'DFIR Emergency Incident Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('source_page', models.CharField(default='homepage', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransmitSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Clearance Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Secure Comm Link')),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('vector', models.CharField(choices=[('consultancy', 'Consultancy as a Service'), ('training', 'Corporate Training'), ('research', 'R&D Collaboration'), ('soc', 'SOC Operations Engagement'), ('vapt', 'Vulnerability Assessment & Penetration Testing'), ('dfir', 'Digital Forensics & Incident Response'), ('grc', 'Governance, Risk & Compliance')], default='consultancy', max_length=50)),
                ('tier', models.CharField(choices=[('standard', 'Standard Analysis'), ('advanced', 'Advanced Architecture'), ('elite', 'Elite Strategic Defense')], default='standard', max_length=50)),
                ('message', models.TextField(verbose_name='Mission Parameters')),
                ('status', models.CharField(choices=[('NEW', 'New Inbound Signal'), ('IN_REVIEW', 'Under Sentinel Triage'), ('ENGAGED', 'Client Engaged / In Discussion'), ('RESOLVED', 'Completed / Contract Signed'), ('ARCHIVED', 'Archived / Closed')], default='NEW', max_length=20)),
                ('assigned_analyst', models.CharField(blank=True, help_text='Analyst handling this lead', max_length=150)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, default='--', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transmit Signal (Inquiry)',
                'verbose_name_plural': 'Transmit Signals (Inquiries)',
                'ordering': ['-created_at'],
            },
        ),
    ]
