# Generated by Django 4.2.30 on 2026-09-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('TERMS', 'Terms & Conditions'), ('PRIVACY', 'Privacy Policy'), ('DPDP', 'DPDP Act 2023 Compliance Notice'), ('SECURITY', 'Responsible Security Disclosure Policy'), ('COOKIE', 'Cookie & Telemetry Policy')], max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='e.g. terms, privacy, dpdp-act', max_length=100, unique=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('effective_date', models.DateField()),
                ('last_reviewed_date', models.DateField(auto_now=True)),
                ('summary', models.TextField(blank=True, help_text='Short executive summary of this legal document')),
                ('content', models.TextField(help_text='Full markdown or HTML text of the legal terms')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal Document & Policy',
                'verbose_name_plural': 'Legal Documents & Policies',
                'ordering': ['doc_type'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='VayuX Systems', max_length=150)),
                ('legal_name', models.CharField(default='VayuX Systems Private Limited', max_length=200)),
                ('tagline', models.CharField(default='Sovereign Cybersecurity R&D · Autonomous Defense', max_length=255)),
                ('support_email', models.EmailField(default='admin@vayux.systems', max_length=254)),
                ('emergency_dfir_email', models.EmailField(default='dfir@vayux.systems', max_length=254)),
                ('careers_email', models.EmailField(default='careers@vayux.systems', max_length=254)),
                ('primary_phone', models.CharField(default='+91-8200677905', max_length=40)),
                ('emergency_phone', models.CharField(default='+91-8200677905', max_length=40)),
                ('headquarters_city', models.CharField(default='Vadodara', max_length=100)),
                ('headquarters_state', models.CharField(default='Gujarat', max_length=100)),
                ('headquarters_country', models.CharField(default='India', max_length=100)),
                ('headquarters_address', models.TextField(default='Vadodara, Gujarat, India - 390001')),
                ('linkedin_url', models.URLField(blank=True, default='https://www.linkedin.com/company/vayux-systems')),
                ('github_url', models.URLField(blank=True, default='https://github.com/vayux-systems')),
                ('twitter_x_url', models.URLField(blank=True, default='https://twitter.com/VayuXSystems')),
                ('soc_sla_response_time', models.CharField(default='Sub-15ms Event Correlation', max_length=50)),
                ('dfir_emergency_sla', models.CharField(default='Sub-4-Hour Deployment Guarantee', max_length=50)),
                ('operating_hours', models.CharField(default='24/7/365 Continuous SOC & Emergency Incident Response', max_length=100)),
                ('copyright_text', models.CharField(default='© 2026 VayuX Systems Private Limited. All rights reserved.', max_length=200)),
                ('is_maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Global Settings',
                'verbose_name_plural': 'Site Global Settings',
            },
        ),
    ]
