# Generated by Django 4.2.30 on 2026-09-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('homepage', 'Homepage FAQ'), ('about', 'About Us / Transparency FAQ'), ('solutions', 'General Solutions FAQ'), ('soc', 'SOC Management FAQ'), ('vapt', 'VAPT Services FAQ'), ('dfir', 'DFIR Incident Response FAQ'), ('grc', 'GRC & DPDP Compliance FAQ'), ('contact', 'Contact & Engagement FAQ')], default='homepage', max_length=50)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(help_text='Clear factual answer formatted for Google rich snippets and AI engines')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ Item & Schema Pair',
                'verbose_name_plural': 'FAQ Items & Schema Pairs',
                'ordering': ['category', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_path', models.CharField(help_text='e.g. /, /about, /solutions/soc, /solutions/dfir, /glossary', max_length=200, unique=True)),
                ('meta_title', models.CharField(help_text='SERP Title (<60 chars)', max_length=200)),
                ('meta_description', models.TextField(help_text='SERP Description (150-160 chars)')),
                ('canonical_url', models.URLField(blank=True, help_text='e.g. https://vayux.systems/solutions/dfir')),
                ('og_image_url', models.URLField(blank=True, default='https://vayux.systems/og-image.png')),
                ('og_type', models.CharField(default='website', max_length=50)),
                ('twitter_card', models.CharField(default='summary_large_image', max_length=50)),
                ('robots_directive', models.CharField(default='index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1', max_length=150)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page SEO & GEO Metadata',
                'verbose_name_plural': 'Page SEO & GEO Metadata',
                'ordering': ['route_path'],
            },
        ),
    ]
