# Generated by Django 4.2.30 on 2026-09-02 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(default='🛡️ Sovereign Defense Architecture', max_length=100)),
                ('hero_title', models.CharField(default='The Genesis of Sovereign Defense', max_length=200)),
                ('hero_subtitle', models.TextField(default='Constructing unassailable defensive architectures through deep R&D and operational threat telemetry.')),
                ('founding_story', models.TextField(help_text='Detailed narrative about VayuX founding and lab mission')),
                ('leadership_quote', models.TextField(default='True cyber sovereignty is not bought off the shelf; it is forged through rigorous offensive research.')),
                ('leader_name', models.CharField(default='Pragnesh Kumar S. Singh', max_length=100)),
                ('leader_title', models.CharField(default='Founder & Chief Technology Officer', max_length=100)),
                ('core_principles', models.JSONField(default=list, help_text="List of principles (e.g. [{'title': 'Autonomous Defense', 'desc': '...'}])")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us Page Content',
                'verbose_name_plural': 'About Us Page Content',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Research Category',
                'verbose_name_plural': 'Research Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(default='Certification', max_length=100)),
                ('issuing_body', models.CharField(blank=True, max_length=150)),
                ('badge_label', models.CharField(default='VERIFIED', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trust Credential / Badge',
                'verbose_name_plural': 'Trust Credentials & Badges',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PageSectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(help_text='Identifier e.g. home-hero, about-hero, solutions-hero, lab-vs-vendor', max_length=100, unique=True)),
                ('badge_text', models.CharField(blank=True, help_text='e.g. 🔒 Encrypted Nexus Channel', max_length=100)),
                ('heading', models.CharField(help_text='Main headline text', max_length=255)),
                ('highlight_text', models.CharField(blank=True, help_text='Part of headline with gradient text', max_length=100)),
                ('subheading', models.TextField(help_text='Detailed lead paragraph or subtitle')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Optional key-value pairs (e.g. metrics, stats)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Section & Heading',
                'verbose_name_plural': 'Page Sections & Headings',
                'ordering': ['section_key'],
            },
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('badge', models.CharField(default='R&D LAB INITIATIVE', max_length=100)),
                ('summary', models.TextField()),
                ('details', models.TextField(blank=True)),
                ('github_repo_url', models.URLField(blank=True)),
                ('live_demo_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'R&D Project / Tool',
                'verbose_name_plural': 'R&D Projects & Tools',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='soc, vapt, dfir, grc', unique=True)),
                ('tagline', models.CharField(max_length=255)),
                ('lead_definition', models.TextField(help_text='Plain-language factual definition for GEO citation extraction')),
                ('full_description', models.TextField()),
                ('sla_commitment', models.CharField(default='Sub-15ms Detection', max_length=100)),
                ('key_metrics', models.JSONField(blank=True, default=list, help_text="[{'label': 'SLA', 'val': '<4h'}]")),
                ('methodology_steps', models.JSONField(default=list, help_text='Ordered list of methodology steps')),
                ('capabilities_list', models.JSONField(default=list, help_text='Bulleted list of included capabilities')),
                ('rd_feedback_loop', models.TextField(help_text='How operational telemetry feeds back into VayuX R&D')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solution & Defense Pillar',
                'verbose_name_plural': 'Solutions & Defense Pillars',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role_designation', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('is_founder', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Architect / Team Member',
                'verbose_name_plural': 'Architects & Team Members',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('short_definition', models.TextField(help_text='2-3 sentence factual definition extracted by Perplexity/ChatGPT')),
                ('why_it_matters', models.TextField(help_text='Why this concept is crucial for enterprise defense')),
                ('key_processes', models.JSONField(default=list, help_text='Numbered list of core processes')),
                ('vayux_approach', models.TextField(help_text='How VayuX applies or defends against this')),
                ('target_search_query', models.CharField(blank=True, help_text="e.g. 'what is dfir in cybersecurity'", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glossary_terms', to='content_cms.solution')),
            ],
            options={
                'verbose_name': 'Glossary Term (GEO)',
                'verbose_name_plural': 'Glossary Terms (GEO)',
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('author_name', models.CharField(default='VayuX Research Team', max_length=150)),
                ('author_role', models.CharField(blank=True, default='Threat Intelligence Division', max_length=150)),
                ('excerpt', models.TextField(help_text='Short abstract / summary for SERP and cards')),
                ('content', models.TextField(help_text='Full markdown or HTML article content')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('read_time_minutes', models.PositiveIntegerField(default=5)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='content_cms.category')),
            ],
            options={
                'verbose_name': 'Research Article / Whitepaper',
                'verbose_name_plural': 'Research Articles & Whitepapers',
                'ordering': ['-published_at'],
            },
        ),
    ]
