# Generated by Django 4.2.30 on 2026-09-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text='ISO country code (e.g. IN, US, DE, GB)', max_length=10, unique=True)),
                ('region_name', models.CharField(default='India', max_length=100)),
                ('framework_name', models.CharField(default='DPDP Act 2023 & CERT-In Directives', max_length=100)),
                ('badge_label', models.CharField(default='SOVEREIGN COMPLIANCE', max_length=100)),
                ('banner_headline', models.CharField(default='Indian Data Sovereignty & DPDP Compliance', max_length=200)),
                ('banner_description', models.TextField(default='VayuX Systems complies with the Digital Personal Data Protection Act 2023 and CERT-In 6-hour cybersecurity reporting directives.')),
                ('emergency_hotline', models.CharField(default='+91-8200677905', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regional Compliance Rule',
                'verbose_name_plural': 'Regional Compliance Rules',
                'ordering': ['country_code'],
            },
        ),
        migrations.CreateModel(
            name='SocNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country_code', models.CharField(default='IN', max_length=10)),
                ('lat', models.FloatField(help_text='Latitude coordinate (e.g. 22.3072 for Vadodara)')),
                ('lng', models.FloatField(help_text='Longitude coordinate (e.g. 73.1812 for Vadodara)')),
                ('node_type', models.CharField(choices=[('PRIMARY_NEXUS', 'Primary Command & R&D Nexus'), ('SOVEREIGN_NODE', 'Sovereign Regional Defense Node'), ('RELAY_GATEWAY', 'Telemetry Relay Gateway')], default='SOVEREIGN_NODE', max_length=30)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Fully Operational (100% SLA)'), ('ELEVATED', 'Elevated Alert Status'), ('MAINTENANCE', 'Scheduled Maintenance')], default='OPERATIONAL', max_length=30)),
                ('latency_ms', models.PositiveIntegerField(default=12, help_text='Average internal event correlation latency in ms')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Global SOC Node',
                'verbose_name_plural': 'Global SOC Nodes',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
